name: theme_mode_builder_example
description: Demonstrates how to use the theme_mode_builder plugin.
publish_to: "none"

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  theme_mode_builder:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
