include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Good packages document everything
    public_member_api_docs: true

    # Utility classes are awesome
    avoid_classes_with_only_static_members: false

    always_specify_types: true

    prefer_const_constructors: true

analyzer:
  errors:
    prefer_const_constructors: error
    always_specify_types: error