include: package:lint/analysis_options_package.yaml

linter:
  rules:
    # Good packages document everything
    public_member_api_docs: true

    # Utility classes are awesome
    avoid_classes_with_only_static_members: false
