name: theme_mode_builder
description: A Flutter package for handling theme in an app and also saving it on the device in a hive box.
version: 1.0.1
# author: Yazeed AlKhalaf <yazeedfady@gmail.com>
homepage: https://github.com/YazeedAlKhalaf/theme_mode_builder

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.0.4
  hive_flutter: ^1.0.0
  stacked: ^2.1.1

dev_dependencies:
  lint: ^1.5.3

flutter:
